export default {
  roomsData: {
    all: {
      name: 'Все комнаты',
    },
    activeRoom: 'all',
    activeTab: 'temperature',
    livingroom: {
      name: 'Зал',
      temperature: 26,
      temperatureOff: false,
      lights: 70,
      lightsOff: false,
      humidity: 60,
      humidityOff: false,
    },
    bedroom: {
      name: 'Спальня',
      temperature: 16,
      temperatureOff: false,
      lights: 0,
      lightsOff: false,
      humidity: 0,
      humidityOff: false,
    },
    kitchen: {
      name: 'Кухня',
      temperature: 16,
      temperatureOff: false,
      lights: 0,
      lightsOff: false,
      humidity: 0,
      humidityOff: false,
    },
    bathroom: {
      name: 'Ванная',
      temperature: 16,
      temperatureOff: false,
      lights: 0,
      lightsOff: false,
      humidity: 0,
      humidityOff: false,
    },
    studio: {
      name: 'Кабинет',
      temperature: 16,
      temperatureOff: false,
      lights: 0,
      lightsOff: false,
      humidity: 0,
      humidityOff: false,
    },
    washingroom: {
      name: 'Прачичная',
      temperature: 16,
      temperatureOff: false,
      lights: 0,
      lightsOff: false,
      humidity: 0,
      humidityOff: false,
    },
  }
};
