export default {
  roomsData: {
    all: {
      name: 'Все комнаты',
    },
    activeRoom: 'all',
    activeTab: 'temperature',
    livingroom: {
      name: 'Зал',
      temperature: 24,
      temperatureOff: false,
      lights: 80,
      lightsOff: false,
      humidity: 60,
      humidityOff: false,
    },
    bedroom: {
      name: 'Спальня',
      temperature: 18,
      temperatureOff: false,
      lights: 15,
      lightsOff: false,
      humidity: 70,
      humidityOff: false,
    },
    kitchen: {
      name: 'Кухня',
      temperature: 22,
      temperatureOff: false,
      lights: 60,
      lightsOff: false,
      humidity: 60,
      humidityOff: false,
    },
    bathroom: {
      name: 'Ванная',
      temperature: 28,
      temperatureOff: false,
      lights: 90,
      lightsOff: false,
      humidity: 20,
      humidityOff: false,
    },
    studio: {
      name: 'Кабинет',
      temperature: 24,
      temperatureOff: false,
      lights: 70,
      lightsOff: false,
      humidity: 60,
      humidityOff: false,
    },
    washingroom: {
      name: 'Прачичная',
      temperature: 18,
      temperatureOff: false,
      lights: 20,
      lightsOff: false,
      humidity: 20,
      humidityOff: false,
    },
  }
};
